api:
  dashboard: false
  debug: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    # http3: {} # Uncomment if you want to enable HTTP/3
    http:
      tls:
        certResolver: letsencrypt
        options: modern

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy

certificatesResolvers:
  letsencrypt:
    acme:
      email: xxx@yyy.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {} 

# Explicit TLS options
tls:
  options:
    modern:
      minVersion: VersionTLS13